version: '3.8'

services:
  tg_bot_pivpn:
    build: .
    container_name: tg_bot_pivpn
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
    volumes:
      - ./data:/app/data
      - /etc/wireguard:/etc/wireguard
      - /usr/bin/wg:/usr/bin/wg
      - /usr/bin/wg-quick:/usr/bin/wg-quick
      - /usr/local/bin/pivpn:/usr/local/bin/pivpn
      - /usr/local/src/pivpn:/usr/local/src/pivpn
      - /opt/pivpn:/opt/pivpn
    network_mode: "host"
